### ISSUE TITLE
Wrong data type when specifying the AWS credentials in connector config

### ISSUE THREAD

**Issue by Chesterone** [trustpilot/kafka-connect-dynamodb#3]
Release 0.9.6

If you run the connector with specified `aws.access.key.id` and `aws.secret.key`, then connector fails with the following error:
java.lang.ClassCastException: org.apache.kafka.common.config.types.Password cannot be cast to java.lang.String
org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:194)
com.trustpilot.connector.dynamodb.DynamoDBSourceConnectorConfig.getAwsAccessKeyId(DynamoDBSourceConnectorConfig.java:164)
com.trustpilot.connector.dynamodb.DynamoDBSourceConnector.start(DynamoDBSourceConnector.java:57)
org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)
org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)
org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)
org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1095)
org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:1091)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)\n

**Comment by NiramayVaidya** [comment]
I am facing the same issue. Did you find a workaround for this @Chesterone?

**Comment by NiramayVaidya** [comment]
This issue is occurring because, as can be seen in the call stack posted by @Chesterone in his comment, when `getString` is called, it expects the input argument to be of type `java.lang.String` but the argument actually provided is of type `org.apache.kafka.common.config.ConfigDef.Type.PASSWORD` for both `aws.access.key.id` and `aws.secret.key` configuration options. Hence, the `java.lang.ClassCastException` is thrown.
This issue can be solved by changing their types to `org.apache.kafka.common.config.ConfigDef.Type.STRING` instead, similar to what has been used for the `aws.region` configuration option.
